# Generated by Django 6.0.5 on 2026-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_deal_next_check_pending_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='pending_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='deal',
            name='pending_message_approved',
            field=models.BooleanField(default=False),
        ),
    ]
