# Generated by Django 6.0.5 on 2026-06-01 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_message_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='regeneration_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='rejection_feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
