# Generated by Django 6.0.5 on 2026-06-01 03:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_deal_pending_message_created_at'),
        ('linkedin', '0018_campaign_pipeline_overrides'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignLead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('linkedin_connection', 'LinkedIn connection'), ('linkedin_invitation', 'LinkedIn invitation'), ('imported_contact', 'Imported contact'), ('linkedin_search', 'LinkedIn search'), ('manual', 'Manual')], default='manual', max_length=32)),
                ('relationship_status', models.CharField(choices=[('connected', 'Connected'), ('invited', 'Invited'), ('unknown', 'Unknown')], default='unknown', max_length=16)),
                ('priority', models.IntegerField(db_index=True, default=100)),
                ('connected_on', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='linkedin.campaign')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_leads', to='crm.lead')),
            ],
            options={
                'verbose_name': 'Campaign lead',
                'verbose_name_plural': 'Campaign leads',
                'indexes': [models.Index(fields=['campaign', 'priority', 'creation_date'], name='crm_campaig_campaig_41e6d6_idx'), models.Index(fields=['campaign', 'relationship_status'], name='crm_campaig_campaig_6ddcf3_idx')],
                'constraints': [models.UniqueConstraint(fields=('campaign', 'lead'), name='unique_campaign_lead')],
            },
        ),
    ]
