# Generated by Django 6.0.5 on 2026-05-29 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0010_remove_freemium_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='website_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='linkedinprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
