# Generated by Django 6.0.5 on 2026-05-29 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0011_campaign_website_url_linkedinprofile_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='require_message_approval',
            field=models.BooleanField(default=False),
        ),
    ]
