# Generated by Django 6.0.5 on 2026-05-31 00:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_message_approval'),
        ('linkedin', '0012_message_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='actionlog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='action_logs', to='crm.lead'),
        ),
    ]
