# Generated by Django 6.0.5 on 2026-05-31 23:34

from pathlib import Path

from django.db import migrations

_PROMPTS_DIR = Path(__file__).parent.parent / "templates" / "prompts"


def _read_j2(filename):
    return (_PROMPTS_DIR / filename).read_text(encoding="utf-8")


_FACT_EXTRACTION_PROMPT = """\
You are an information-extraction assistant. Your job is to read the input
text and produce a flat list of atomic, self-contained factual statements
about the lead (the person we are talking to).

Rules:
- Each fact must be a complete sentence that stands on its own.
- Prefer concrete, durable facts (identity, role, employer, location, career
  arc, stated goals, expressed concerns) over fleeting commentary.
- Do not invent facts. If the text does not assert it, do not include it.
- Do not duplicate facts. Merge near-duplicates.
- Keep each fact short (under ~25 words).
- Return between 0 and 30 facts. Empty list is acceptable when there is
  nothing useful to extract.
- The input may contain messages from both sides of a conversation, tagged
  [Me] and [Lead]. Extract facts about the LEAD only. Use [Me] messages
  solely as context to disambiguate the lead's replies (e.g. if the lead
  says "yes", use the preceding [Me] message to understand what they agreed
  to). Never extract facts about what [Me] said, offered, or asked.
- Paraphrase trap: when the lead opens their reply by paraphrasing or
  summarising what [Me] said ("I understand you are building X",
  "As you said...", "So you're trying to...", "Por lo que entiendo...",
  "Entiendo que tú..."), that sentence describes [Me]'s product or pitch,
  NOT the lead's own situation. Skip it entirely. Only extract facts where
  the lead describes their own experience, opinions, goals, or situation.

Output ONLY a JSON object with this exact shape (no markdown, no prose):
{"facts": ["Fact one.", "Fact two."]}
"""

_DEFAULT_UPDATE_MEMORY_PROMPT = """You are a smart memory manager which controls the memory of a system.
You can perform four operations: (1) add into the memory, (2) update the memory, (3) delete from the memory, and (4) no change.

Based on the above four operations, the memory will change.

Compare newly retrieved facts with the existing memory. For each new fact, decide whether to:
- ADD: Add it to the memory as a new element
- UPDATE: Update an existing memory element
- DELETE: Delete an existing memory element
- NONE: Make no change (if the fact is already present or irrelevant)

There are specific guidelines to select which operation to perform:

1. **Add**: If the retrieved facts contain new information not present in the memory, then you have to add it by generating a new ID in the id field.
- **Example**:
    - Old Memory:
        [
            {
                "id" : "0",
                "text" : "User is a software engineer"
            }
        ]
    - Retrieved facts: ["Name is John"]
    - New Memory:
        {
            "memory" : [
                {
                    "id" : "0",
                    "text" : "User is a software engineer",
                    "event" : "NONE"
                },
                {
                    "id" : "1",
                    "text" : "Name is John",
                    "event" : "ADD"
                }
            ]

        }

2. **Update**: If the retrieved facts contain information that is already present in the memory but the information is totally different, then you have to update it.
If the retrieved fact contains information that conveys the same thing as the elements present in the memory, then you have to keep the fact which has the most information.
Example (a) -- if the memory contains "User likes to play cricket" and the retrieved fact is "Loves to play cricket with friends", then update the memory with the retrieved facts.
Example (b) -- if the memory contains "Likes cheese pizza" and the retrieved fact is "Loves cheese pizza", then you do not need to update it because they convey the same information.
If the direction is to update the memory, then you have to update it.
Please keep in mind while updating you have to keep the same ID.
Please note to return the IDs in the output from the input IDs only and do not generate any new ID.
- **Example**:
    - Old Memory:
        [
            {
                "id" : "0",
                "text" : "I really like cheese pizza"
            },
            {
                "id" : "1",
                "text" : "User is a software engineer"
            },
            {
                "id" : "2",
                "text" : "User likes to play cricket"
            }
        ]
    - Retrieved facts: ["Loves chicken pizza", "Loves to play cricket with friends"]
    - New Memory:
        {
        "memory" : [
                {
                    "id" : "0",
                    "text" : "Loves cheese and chicken pizza",
                    "event" : "UPDATE",
                    "old_memory" : "I really like cheese pizza"
                },
                {
                    "id" : "1",
                    "text" : "User is a software engineer",
                    "event" : "NONE"
                },
                {
                    "id" : "2",
                    "text" : "Loves to play cricket with friends",
                    "event" : "UPDATE",
                    "old_memory" : "User likes to play cricket"
                }
            ]
        }


3. **Delete**: If the retrieved facts contain information that contradicts the information present in the memory, then you have to delete it. Or if the direction is to delete the memory, then you have to delete it.
Please note to return the IDs in the output from the input IDs only and do not generate any new ID.
- **Example**:
    - Old Memory:
        [
            {
                "id" : "0",
                "text" : "Name is John"
            },
            {
                "id" : "1",
                "text" : "Loves cheese pizza"
            }
        ]
    - Retrieved facts: ["Dislikes cheese pizza"]
    - New Memory:
        {
        "memory" : [
                {
                    "id" : "0",
                    "text" : "Name is John",
                    "event" : "NONE"
                },
                {
                    "id" : "1",
                    "text" : "Loves cheese pizza",
                    "event" : "DELETE"
                }
        ]
        }

4. **No Change**: If the retrieved facts contain information that is already present in the memory, then you do not need to make any changes.
- **Example**:
    - Old Memory:
        [
            {
                "id" : "0",
                "text" : "Name is John"
            },
            {
                "id" : "1",
                "text" : "Loves cheese pizza"
            }
        ]
    - Retrieved facts: ["Name is John"]
    - New Memory:
        {
        "memory" : [
                {
                    "id" : "0",
                    "text" : "Name is John",
                    "event" : "NONE"
                },
                {
                    "id" : "1",
                    "text" : "Loves cheese pizza",
                    "event" : "NONE"
                }
            ]
        }
"""

_PROMPTS = [
    {
        "key": "qualification",
        "name": "Lead Qualification",
        "description": (
            "LLM prompt used to qualify a LinkedIn profile as a prospect. "
            "Jinja2 variables: {{ product_docs }}, {{ campaign_objective }}, {{ profile_text }}."
        ),
        "body": _read_j2("qualify_lead.j2"),
    },
    {
        "key": "follow_up_agent",
        "name": "Follow-up Agent",
        "description": (
            "LLM system prompt for the follow-up agent. Controls discovery vs. pitch mode, "
            "timing, greetings, and action selection. "
            "Jinja2 variables: {{ self_name }}, {{ contact_email }}, {{ product_docs }}, "
            "{{ campaign_objective }}, {{ booking_link }}, {{ website_url }}, "
            "{{ profile_summary }}, {{ chat_summary }}, {{ recent_messages }}, "
            "{{ today }}, {{ days_since_last_outgoing }}, {{ unanswered_outgoing }}, "
            "{{ reengagement_greeting_days }}."
        ),
        "body": _read_j2("follow_up_agent.j2"),
    },
    {
        "key": "profile_fact_extraction",
        "name": "Profile Fact Extraction",
        "description": (
            "LLM system prompt for extracting atomic facts about a lead from their "
            "LinkedIn profile text or conversation transcript. No Jinja2 variables — "
            "used as a static system prompt; identity binding is appended at runtime."
        ),
        "body": _FACT_EXTRACTION_PROMPT,
    },
    {
        "key": "chat_fact_reconciliation",
        "name": "Chat Fact Reconciliation",
        "description": (
            "mem0-style memory manager prompt used to reconcile newly extracted facts "
            "against the existing chat_summary fact list (ADD/UPDATE/DELETE/NONE). "
            "No Jinja2 variables — the surrounding wrapper (old memory + new facts) "
            "is assembled at runtime by get_update_memory_messages()."
        ),
        "body": _DEFAULT_UPDATE_MEMORY_PROMPT,
    },
    {
        "key": "connection_message",
        "name": "Connection Request Message",
        "description": (
            "LLM prompt for generating a personalised connection request note. "
            "Currently unused — connection requests are sent without a note. "
            "Reserved for future use."
        ),
        "body": "",
    },
]


def create_defaults(apps, schema_editor):
    PromptTemplate = apps.get_model("linkedin", "PromptTemplate")
    for data in _PROMPTS:
        PromptTemplate.objects.get_or_create(key=data["key"], defaults={
            "name": data["name"],
            "description": data["description"],
            "body": data["body"],
        })


def delete_defaults(apps, schema_editor):
    PromptTemplate = apps.get_model("linkedin", "PromptTemplate")
    PromptTemplate.objects.filter(key__in=[p["key"] for p in _PROMPTS]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0014_prompttemplate'),
    ]

    operations = [
        migrations.RunPython(create_defaults, delete_defaults),
    ]
