# Generated by Django 6.0.5 on 2026-06-01 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0015_prompttemplate_defaults'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignPromptOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_key', models.CharField(choices=[('qualification', 'qualification'), ('follow_up_agent', 'follow_up_agent'), ('profile_fact_extraction', 'profile_fact_extraction'), ('chat_fact_reconciliation', 'chat_fact_reconciliation'), ('connection_message', 'connection_message')], max_length=100)),
                ('body', models.TextField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_overrides', to='linkedin.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Prompt Override',
                'verbose_name_plural': 'Campaign Prompt Overrides',
                'unique_together': {('campaign', 'prompt_key')},
            },
        ),
    ]
