# Generated by Django 6.0.5 on 2026-06-01 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0016_campaignpromptoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='check_pending_daily_cap',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='connect_daily_limit',
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='follow_up_cooldown_hours',
            field=models.PositiveIntegerField(default=72),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='follow_up_daily_limit',
            field=models.PositiveIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='gpr_qualification_threshold',
            field=models.FloatField(default=0.85),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='max_followups_without_reply',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='reengagement_greeting_days',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
