# Generated by Django 6.0.5 on 2026-06-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0017_siteconfig_pipeline_conditions'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='check_pending_daily_cap',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='connect_daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='follow_up_cooldown_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='follow_up_daily_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='gpr_qualification_threshold',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='max_followups_without_reply',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='reengagement_greeting_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
