# Generated by Django 6.0.5 on 2026-06-01 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0018_campaign_pipeline_overrides'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='min_qualification_observations_before_connect',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='preconnect_qualification_batch_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='min_qualification_observations_before_connect',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='preconnect_qualification_batch_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
