# Generated by Django 6.0.5 on 2026-06-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0019_campaign_min_qualification_observations_before_connect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='llm_max_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='llm_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_max_tokens',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='siteconfig',
            name='llm_temperature',
            field=models.FloatField(default=0.7),
        ),
    ]
