# Generated by Django 6.0.5 on 2026-06-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkedin', '0020_add_llm_temperature_max_tokens'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfig',
            name='display_timezone',
            field=models.CharField(default='America/Bogota', max_length=100),
        ),
    ]
